In [1]:
print('hi')

hi


In [2]:
import pandas as pd

#open this file with pandas data/papers_dictionary.json
papers = pd.read_json('./data/papers_dictionary.json')
#the dataframe is flipped, so we need to flip it back
papers = papers.T
papers


title  \
0        Pairwise Neural Machine Translation Evaluation   
1     Spectral Learning of Mixture of Hidden Markov ...   
2              On Conceptual Labeling of a Bag of Words   
3      Multi-Instance Learning with Distribution Change   
4     Love Thy Neighbors: Image Annotation by Exploi...   
...                                                 ...   
2441  Solving Imperfect Information Games Using Deco...   
2442  Interplanetary Trajectory Planning with Monte ...   
2443                  Learning with Relaxed Supervision   
2444  Nighttime Haze Removal with Glow and Multiple ...   
2445  A Decision-Theoretic Approach to Natural Langu...   

                                               abstract  \
0     We present a novel framework for machine trans...   
1     In this paper, we propose a learning approach ...   
2     In natural language processing and information...   
3     Multi-instance learning deals with tasks where...   
4     Some images that are difficult to recognize on...   
...                                                 ...   
2441  Decomposition, i.e., independently analyzing p...   
2442  Planning an interplanetary trajectory is a ver...   
2443  For weakly-supervised problems with determinis...   
2444  This paper focuses on dehazing nighttime image...   
2445  We study the problem of generating an English ...   

                                                authors  
0     [Francisco Guzmán, Shafiq R. Joty, Lluís Màrqu...  
1      [Y. Cem Sübakan, Johannes Traa, Paris Smaragdis]  
2     [Xiangyan Sun, Yanghua Xiao, Haixun Wang, Wei ...  
3                          [Weijia Zhang, Zhi-Hua Zhou]  
4          [Justin Johnson, Lamberto Ballan, Feifei Li]  
...                                                 ...  
2441  [Neil Burch, Michael Johanson, Michael H. Bowl...  
2442                        [Daniel Hennes, Dario Izzo]  
2443                    [Jacob Steinhardt, Percy Liang]  
2444            [Yu Li, Robby T. Tan, Michael S. Brown]  
2445                      [Nathan McKinley, Soumya Ray]  

[2446 rows x 3 columns]

In [3]:
reviewers = pd.read_json('./data/reviewers_dictionary.json')
reviewers = reviewers.T
reviewers



name                                             papers
0                Biao Zhang  [{'title': 'A modified migrating birds optimiz...
1              Mingwen Wang  [{'title': 'Fast Horizon Estimation via Deep H...
2      Alessandro Moschitti  [{'title': 'Multi-lingual opinion mining on Yo...
3         Karin M. Verspoor  [{'title': 'An expanded evaluation of protein ...
4               Borja Balle  [{'title': 'Privacy Amplification by Mixing an...
...                     ...                                                ...
2478       Gautam Dasarathy  [{'title': 'Active Learning Algorithms for Gra...
2479  Baharan Mirzasoleiman  [{'title': 'Fast Distributed Submodular Cover:...
2480          Nikos Vlassis  [{'title': 'Posterior Sampling for Large Scale...
2481                Luo Luo  [{'title': 'Approximate Newton Methods and The...
2482      Émilie Chouzenoux  [{'title': 'A Data Augmentation Approach for S...

[2483 rows x 2 columns]

In [7]:
reviewers['papers'][0][0]['title']

'A modified migrating birds optimization for solving the steelmaking-continuous casting problem with variable processing times'

In [23]:
import torch
#load tensor_data.pl with torch
data = torch.load('./data/tensor_data.pl')
print('KEYS',data.keys())


KEYS dict_keys(['r_subject', 'p_subject', 'p_title', 'label', 'tpms'])


In [36]:
data['r_subject']['indices'][0].shape

torch.Size([12252])

In [ ]:
data['p_subject']

{'indices': tensor([[   0,    0,    0,  ..., 2445, 2445, 2445],
         [  14,   57,  110,  ...,  151,  195,  341]]),
 'values': tensor([1., 1., 1.,  ..., 1., 1., 1.], dtype=torch.float64),
 'size': torch.Size([2446, 368])}

In [ ]:
data['p_title']


tensor([[   0,    0,    0,  ..., 2445, 2445, 2445],
        [ 548,  627,  136,  ...,  901,  620,  330]])

In [ ]:
print(data['label'].shape) #les bids !
data['label']

(2483, 2446)


array([[3., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 2., 0., 0.],
       ...,
       [0., 2., 0., ..., 0., 0., 2.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
print(data['tpms'].shape)   #les tpms scores
data['tpms']

torch.Size([2483, 2446])


tensor([[0.8745, 0.4668, 0.6528,  ..., 0.7446, 0.4734, 0.5527],
        [0.7217, 0.5415, 0.5610,  ..., 0.4519, 0.5322, 0.5483],
        [0.8735, 0.1735, 0.7925,  ..., 0.3469, 0.3774, 0.4888],
        ...,
        [0.4810, 0.7402, 0.4158,  ..., 0.7061, 0.5845, 0.7681],
        [0.5356, 0.7178, 0.5400,  ..., 0.6958, 0.5303, 0.5581],
        [0.4468, 0.7202, 0.4678,  ..., 0.7319, 0.5156, 0.5068]])